/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CodespacesPreFlightWithRepoForAuthenticatedUser200ResponseDefaults
 */
public class CodespacesPreFlightWithRepoForAuthenticatedUser200ResponseDefaultsTest {
    private final CodespacesPreFlightWithRepoForAuthenticatedUser200ResponseDefaults model = new CodespacesPreFlightWithRepoForAuthenticatedUser200ResponseDefaults();

    /**
     * Model tests for CodespacesPreFlightWithRepoForAuthenticatedUser200ResponseDefaults
     */
    @Test
    public void testCodespacesPreFlightWithRepoForAuthenticatedUser200ResponseDefaults() {
        // TODO: test CodespacesPreFlightWithRepoForAuthenticatedUser200ResponseDefaults
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'devcontainerPath'
     */
    @Test
    public void devcontainerPathTest() {
        // TODO: test devcontainerPath
    }

}
