/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CodespacesUpdateForAuthenticatedUserRequest
 */
public class CodespacesUpdateForAuthenticatedUserRequestTest {
    private final CodespacesUpdateForAuthenticatedUserRequest model = new CodespacesUpdateForAuthenticatedUserRequest();

    /**
     * Model tests for CodespacesUpdateForAuthenticatedUserRequest
     */
    @Test
    public void testCodespacesUpdateForAuthenticatedUserRequest() {
        // TODO: test CodespacesUpdateForAuthenticatedUserRequest
    }

    /**
     * Test the property 'machine'
     */
    @Test
    public void machineTest() {
        // TODO: test machine
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'recentFolders'
     */
    @Test
    public void recentFoldersTest() {
        // TODO: test recentFolders
    }

}
