/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.NullableCodeOfConductSimple;
import org.openapitools.client.model.NullableCommunityHealthFile;
import org.openapitools.client.model.NullableLicenseSimple;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CommunityProfileFiles
 */
public class CommunityProfileFilesTest {
    private final CommunityProfileFiles model = new CommunityProfileFiles();

    /**
     * Model tests for CommunityProfileFiles
     */
    @Test
    public void testCommunityProfileFiles() {
        // TODO: test CommunityProfileFiles
    }

    /**
     * Test the property 'codeOfConduct'
     */
    @Test
    public void codeOfConductTest() {
        // TODO: test codeOfConduct
    }

    /**
     * Test the property 'codeOfConductFile'
     */
    @Test
    public void codeOfConductFileTest() {
        // TODO: test codeOfConductFile
    }

    /**
     * Test the property 'license'
     */
    @Test
    public void licenseTest() {
        // TODO: test license
    }

    /**
     * Test the property 'contributing'
     */
    @Test
    public void contributingTest() {
        // TODO: test contributing
    }

    /**
     * Test the property 'readme'
     */
    @Test
    public void readmeTest() {
        // TODO: test readme
    }

    /**
     * Test the property 'issueTemplate'
     */
    @Test
    public void issueTemplateTest() {
        // TODO: test issueTemplate
    }

    /**
     * Test the property 'pullRequestTemplate'
     */
    @Test
    public void pullRequestTemplateTest() {
        // TODO: test pullRequestTemplate
    }

}
