/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Deployment1Payload
 */
public class Deployment1PayloadTest {
    private final Deployment1Payload model = new Deployment1Payload();

    /**
     * Model tests for Deployment1Payload
     */
    @Test
    public void testDeployment1Payload() {
        // TODO: test Deployment1Payload
    }

}
