/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OidcCustomSub
 */
public class OidcCustomSubTest {
    private final OidcCustomSub model = new OidcCustomSub();

    /**
     * Model tests for OidcCustomSub
     */
    @Test
    public void testOidcCustomSub() {
        // TODO: test OidcCustomSub
    }

    /**
     * Test the property 'includeClaimKeys'
     */
    @Test
    public void includeClaimKeysTest() {
        // TODO: test includeClaimKeys
    }

}
