/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.WebhookDiscussionCommentEditedChangesBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookProjectCardConvertedChanges
 */
public class WebhookProjectCardConvertedChangesTest {
    private final WebhookProjectCardConvertedChanges model = new WebhookProjectCardConvertedChanges();

    /**
     * Model tests for WebhookProjectCardConvertedChanges
     */
    @Test
    public void testWebhookProjectCardConvertedChanges() {
        // TODO: test WebhookProjectCardConvertedChanges
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

}
