/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.WebhookSecurityAdvisoryPublishedSecurityAdvisoryCvss;
import org.openapitools.client.model.WebhookSecurityAdvisoryPublishedSecurityAdvisoryCwesInner;
import org.openapitools.client.model.WebhookSecurityAdvisoryPublishedSecurityAdvisoryIdentifiersInner;
import org.openapitools.client.model.WebhookSecurityAdvisoryPublishedSecurityAdvisoryReferencesInner;
import org.openapitools.client.model.WebhookSecurityAdvisoryPublishedSecurityAdvisoryVulnerabilitiesInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookSecurityAdvisoryPublishedSecurityAdvisory
 */
public class WebhookSecurityAdvisoryPublishedSecurityAdvisoryTest {
    private final WebhookSecurityAdvisoryPublishedSecurityAdvisory model = new WebhookSecurityAdvisoryPublishedSecurityAdvisory();

    /**
     * Model tests for WebhookSecurityAdvisoryPublishedSecurityAdvisory
     */
    @Test
    public void testWebhookSecurityAdvisoryPublishedSecurityAdvisory() {
        // TODO: test WebhookSecurityAdvisoryPublishedSecurityAdvisory
    }

    /**
     * Test the property 'cvss'
     */
    @Test
    public void cvssTest() {
        // TODO: test cvss
    }

    /**
     * Test the property 'cwes'
     */
    @Test
    public void cwesTest() {
        // TODO: test cwes
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'ghsaId'
     */
    @Test
    public void ghsaIdTest() {
        // TODO: test ghsaId
    }

    /**
     * Test the property 'identifiers'
     */
    @Test
    public void identifiersTest() {
        // TODO: test identifiers
    }

    /**
     * Test the property 'publishedAt'
     */
    @Test
    public void publishedAtTest() {
        // TODO: test publishedAt
    }

    /**
     * Test the property 'references'
     */
    @Test
    public void referencesTest() {
        // TODO: test references
    }

    /**
     * Test the property 'severity'
     */
    @Test
    public void severityTest() {
        // TODO: test severity
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'vulnerabilities'
     */
    @Test
    public void vulnerabilitiesTest() {
        // TODO: test vulnerabilities
    }

    /**
     * Test the property 'withdrawnAt'
     */
    @Test
    public void withdrawnAtTest() {
        // TODO: test withdrawnAt
    }

}
