/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.Enterprise;
import org.openapitools.client.model.IssueComment1;
import org.openapitools.client.model.OrganizationSimple;
import org.openapitools.client.model.Repository;
import org.openapitools.client.model.SimpleInstallation;
import org.openapitools.client.model.SimpleUser;
import org.openapitools.client.model.WebhookIssueCommentDeletedIssue;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookIssueCommentDeleted
 */
public class WebhookIssueCommentDeletedTest {
    private final WebhookIssueCommentDeleted model = new WebhookIssueCommentDeleted();

    /**
     * Model tests for WebhookIssueCommentDeleted
     */
    @Test
    public void testWebhookIssueCommentDeleted() {
        // TODO: test WebhookIssueCommentDeleted
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'enterprise'
     */
    @Test
    public void enterpriseTest() {
        // TODO: test enterprise
    }

    /**
     * Test the property 'installation'
     */
    @Test
    public void installationTest() {
        // TODO: test installation
    }

    /**
     * Test the property 'issue'
     */
    @Test
    public void issueTest() {
        // TODO: test issue
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'repository'
     */
    @Test
    public void repositoryTest() {
        // TODO: test repository
    }

    /**
     * Test the property 'sender'
     */
    @Test
    public void senderTest() {
        // TODO: test sender
    }

}
