/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookPackagePublishedPackagePackageVersionContainerMetadataTag
 */
public class WebhookPackagePublishedPackagePackageVersionContainerMetadataTagTest {
    private final WebhookPackagePublishedPackagePackageVersionContainerMetadataTag model = new WebhookPackagePublishedPackagePackageVersionContainerMetadataTag();

    /**
     * Model tests for WebhookPackagePublishedPackagePackageVersionContainerMetadataTag
     */
    @Test
    public void testWebhookPackagePublishedPackagePackageVersionContainerMetadataTag() {
        // TODO: test WebhookPackagePublishedPackagePackageVersionContainerMetadataTag
    }

    /**
     * Test the property 'digest'
     */
    @Test
    public void digestTest() {
        // TODO: test digest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
