/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.PullRequestReviewComment1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookPullRequestReviewThreadUnresolvedThread
 */
public class WebhookPullRequestReviewThreadUnresolvedThreadTest {
    private final WebhookPullRequestReviewThreadUnresolvedThread model = new WebhookPullRequestReviewThreadUnresolvedThread();

    /**
     * Model tests for WebhookPullRequestReviewThreadUnresolvedThread
     */
    @Test
    public void testWebhookPullRequestReviewThreadUnresolvedThread() {
        // TODO: test WebhookPullRequestReviewThreadUnresolvedThread
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'nodeId'
     */
    @Test
    public void nodeIdTest() {
        // TODO: test nodeId
    }

}
