/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookMarketplacePurchaseCancelledMarketplacePurchaseAllOfPlan
 */
public class WebhookMarketplacePurchaseCancelledMarketplacePurchaseAllOfPlanTest {
    private final WebhookMarketplacePurchaseCancelledMarketplacePurchaseAllOfPlan model = new WebhookMarketplacePurchaseCancelledMarketplacePurchaseAllOfPlan();

    /**
     * Model tests for WebhookMarketplacePurchaseCancelledMarketplacePurchaseAllOfPlan
     */
    @Test
    public void testWebhookMarketplacePurchaseCancelledMarketplacePurchaseAllOfPlan() {
        // TODO: test WebhookMarketplacePurchaseCancelledMarketplacePurchaseAllOfPlan
    }

    /**
     * Test the property 'bullets'
     */
    @Test
    public void bulletsTest() {
        // TODO: test bullets
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'hasFreeTrial'
     */
    @Test
    public void hasFreeTrialTest() {
        // TODO: test hasFreeTrial
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'monthlyPriceInCents'
     */
    @Test
    public void monthlyPriceInCentsTest() {
        // TODO: test monthlyPriceInCents
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'priceModel'
     */
    @Test
    public void priceModelTest() {
        // TODO: test priceModel
    }

    /**
     * Test the property 'unitName'
     */
    @Test
    public void unitNameTest() {
        // TODO: test unitName
    }

    /**
     * Test the property 'yearlyPriceInCents'
     */
    @Test
    public void yearlyPriceInCentsTest() {
        // TODO: test yearlyPriceInCents
    }

}
