/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Enterprise;
import org.openapitools.client.model.Installation;
import org.openapitools.client.model.OrganizationSimple;
import org.openapitools.client.model.PersonalAccessTokenRequestRepositoriesInner;
import org.openapitools.client.model.Repository;
import org.openapitools.client.model.SimpleUser;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookInstallationRepositoriesRemoved
 */
public class WebhookInstallationRepositoriesRemovedTest {
    private final WebhookInstallationRepositoriesRemoved model = new WebhookInstallationRepositoriesRemoved();

    /**
     * Model tests for WebhookInstallationRepositoriesRemoved
     */
    @Test
    public void testWebhookInstallationRepositoriesRemoved() {
        // TODO: test WebhookInstallationRepositoriesRemoved
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'enterprise'
     */
    @Test
    public void enterpriseTest() {
        // TODO: test enterprise
    }

    /**
     * Test the property 'installation'
     */
    @Test
    public void installationTest() {
        // TODO: test installation
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'repositoriesAdded'
     */
    @Test
    public void repositoriesAddedTest() {
        // TODO: test repositoriesAdded
    }

    /**
     * Test the property 'repositoriesRemoved'
     */
    @Test
    public void repositoriesRemovedTest() {
        // TODO: test repositoriesRemoved
    }

    /**
     * Test the property 'repository'
     */
    @Test
    public void repositoryTest() {
        // TODO: test repository
    }

    /**
     * Test the property 'repositorySelection'
     */
    @Test
    public void repositorySelectionTest() {
        // TODO: test repositorySelection
    }

    /**
     * Test the property 'requester'
     */
    @Test
    public void requesterTest() {
        // TODO: test requester
    }

    /**
     * Test the property 'sender'
     */
    @Test
    public void senderTest() {
        // TODO: test sender
    }

}
