/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.WorkflowUsageBillableUBUNTU;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkflowUsageBillable
 */
public class WorkflowUsageBillableTest {
    private final WorkflowUsageBillable model = new WorkflowUsageBillable();

    /**
     * Model tests for WorkflowUsageBillable
     */
    @Test
    public void testWorkflowUsageBillable() {
        // TODO: test WorkflowUsageBillable
    }

    /**
     * Test the property 'UBUNTU'
     */
    @Test
    public void UBUNTUTest() {
        // TODO: test UBUNTU
    }

    /**
     * Test the property 'MACOS'
     */
    @Test
    public void MACOSTest() {
        // TODO: test MACOS
    }

    /**
     * Test the property 'WINDOWS'
     */
    @Test
    public void WINDOWSTest() {
        // TODO: test WINDOWS
    }

}
