/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ActionsCacheUsageOrgEnterprise
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-09T20:37:23.111113500+10:00[Australia/Brisbane]")
public class ActionsCacheUsageOrgEnterprise {
  public static final String SERIALIZED_NAME_TOTAL_ACTIVE_CACHES_COUNT = "total_active_caches_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_ACTIVE_CACHES_COUNT)
  private Integer totalActiveCachesCount;

  public static final String SERIALIZED_NAME_TOTAL_ACTIVE_CACHES_SIZE_IN_BYTES = "total_active_caches_size_in_bytes";
  @SerializedName(SERIALIZED_NAME_TOTAL_ACTIVE_CACHES_SIZE_IN_BYTES)
  private Integer totalActiveCachesSizeInBytes;

  public ActionsCacheUsageOrgEnterprise() {
  }

  public ActionsCacheUsageOrgEnterprise totalActiveCachesCount(Integer totalActiveCachesCount) {
    
    this.totalActiveCachesCount = totalActiveCachesCount;
    return this;
  }

   /**
   * The count of active caches across all repositories of an enterprise or an organization.
   * @return totalActiveCachesCount
  **/
  @javax.annotation.Nonnull

  public Integer getTotalActiveCachesCount() {
    return totalActiveCachesCount;
  }


  public void setTotalActiveCachesCount(Integer totalActiveCachesCount) {
    this.totalActiveCachesCount = totalActiveCachesCount;
  }


  public ActionsCacheUsageOrgEnterprise totalActiveCachesSizeInBytes(Integer totalActiveCachesSizeInBytes) {
    
    this.totalActiveCachesSizeInBytes = totalActiveCachesSizeInBytes;
    return this;
  }

   /**
   * The total size in bytes of all active cache items across all repositories of an enterprise or an organization.
   * @return totalActiveCachesSizeInBytes
  **/
  @javax.annotation.Nonnull

  public Integer getTotalActiveCachesSizeInBytes() {
    return totalActiveCachesSizeInBytes;
  }


  public void setTotalActiveCachesSizeInBytes(Integer totalActiveCachesSizeInBytes) {
    this.totalActiveCachesSizeInBytes = totalActiveCachesSizeInBytes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionsCacheUsageOrgEnterprise actionsCacheUsageOrgEnterprise = (ActionsCacheUsageOrgEnterprise) o;
    return Objects.equals(this.totalActiveCachesCount, actionsCacheUsageOrgEnterprise.totalActiveCachesCount) &&
        Objects.equals(this.totalActiveCachesSizeInBytes, actionsCacheUsageOrgEnterprise.totalActiveCachesSizeInBytes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalActiveCachesCount, totalActiveCachesSizeInBytes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionsCacheUsageOrgEnterprise {\n");
    sb.append("    totalActiveCachesCount: ").append(toIndentedString(totalActiveCachesCount)).append("\n");
    sb.append("    totalActiveCachesSizeInBytes: ").append(toIndentedString(totalActiveCachesSizeInBytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("total_active_caches_count");
    openapiFields.add("total_active_caches_size_in_bytes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("total_active_caches_count");
    openapiRequiredFields.add("total_active_caches_size_in_bytes");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ActionsCacheUsageOrgEnterprise
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ActionsCacheUsageOrgEnterprise.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ActionsCacheUsageOrgEnterprise is not found in the empty JSON string", ActionsCacheUsageOrgEnterprise.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ActionsCacheUsageOrgEnterprise.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ActionsCacheUsageOrgEnterprise` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ActionsCacheUsageOrgEnterprise.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ActionsCacheUsageOrgEnterprise.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ActionsCacheUsageOrgEnterprise' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ActionsCacheUsageOrgEnterprise> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ActionsCacheUsageOrgEnterprise.class));

       return (TypeAdapter<T>) new TypeAdapter<ActionsCacheUsageOrgEnterprise>() {
           @Override
           public void write(JsonWriter out, ActionsCacheUsageOrgEnterprise value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ActionsCacheUsageOrgEnterprise read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ActionsCacheUsageOrgEnterprise given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ActionsCacheUsageOrgEnterprise
  * @throws IOException if the JSON string is invalid with respect to ActionsCacheUsageOrgEnterprise
  */
  public static ActionsCacheUsageOrgEnterprise fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ActionsCacheUsageOrgEnterprise.class);
  }

 /**
  * Convert an instance of ActionsCacheUsageOrgEnterprise to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

