/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ActionsReviewPendingDeploymentsForRunRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-09T20:37:23.111113500+10:00[Australia/Brisbane]")
public class ActionsReviewPendingDeploymentsForRunRequest {
  public static final String SERIALIZED_NAME_ENVIRONMENT_IDS = "environment_ids";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT_IDS)
  private List<Integer> environmentIds = new ArrayList<>();

  /**
   * Whether to approve or reject deployment to the specified environments.
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    APPROVED("approved"),
    
    REJECTED("rejected");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private StateEnum state;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public ActionsReviewPendingDeploymentsForRunRequest() {
  }

  public ActionsReviewPendingDeploymentsForRunRequest environmentIds(List<Integer> environmentIds) {
    
    this.environmentIds = environmentIds;
    return this;
  }

  public ActionsReviewPendingDeploymentsForRunRequest addEnvironmentIdsItem(Integer environmentIdsItem) {
    if (this.environmentIds == null) {
      this.environmentIds = new ArrayList<>();
    }
    this.environmentIds.add(environmentIdsItem);
    return this;
  }

   /**
   * The list of environment ids to approve or reject
   * @return environmentIds
  **/
  @javax.annotation.Nonnull

  public List<Integer> getEnvironmentIds() {
    return environmentIds;
  }


  public void setEnvironmentIds(List<Integer> environmentIds) {
    this.environmentIds = environmentIds;
  }


  public ActionsReviewPendingDeploymentsForRunRequest state(StateEnum state) {
    
    this.state = state;
    return this;
  }

   /**
   * Whether to approve or reject deployment to the specified environments.
   * @return state
  **/
  @javax.annotation.Nonnull

  public StateEnum getState() {
    return state;
  }


  public void setState(StateEnum state) {
    this.state = state;
  }


  public ActionsReviewPendingDeploymentsForRunRequest comment(String comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * A comment to accompany the deployment review
   * @return comment
  **/
  @javax.annotation.Nonnull

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    this.comment = comment;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionsReviewPendingDeploymentsForRunRequest actionsReviewPendingDeploymentsForRunRequest = (ActionsReviewPendingDeploymentsForRunRequest) o;
    return Objects.equals(this.environmentIds, actionsReviewPendingDeploymentsForRunRequest.environmentIds) &&
        Objects.equals(this.state, actionsReviewPendingDeploymentsForRunRequest.state) &&
        Objects.equals(this.comment, actionsReviewPendingDeploymentsForRunRequest.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(environmentIds, state, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionsReviewPendingDeploymentsForRunRequest {\n");
    sb.append("    environmentIds: ").append(toIndentedString(environmentIds)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("environment_ids");
    openapiFields.add("state");
    openapiFields.add("comment");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("environment_ids");
    openapiRequiredFields.add("state");
    openapiRequiredFields.add("comment");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ActionsReviewPendingDeploymentsForRunRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ActionsReviewPendingDeploymentsForRunRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ActionsReviewPendingDeploymentsForRunRequest is not found in the empty JSON string", ActionsReviewPendingDeploymentsForRunRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ActionsReviewPendingDeploymentsForRunRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ActionsReviewPendingDeploymentsForRunRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ActionsReviewPendingDeploymentsForRunRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the required json array is present
      if (jsonObj.get("environment_ids") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("environment_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `environment_ids` to be an array in the JSON string but got `%s`", jsonObj.get("environment_ids").toString()));
      }
      if (!jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if (!jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ActionsReviewPendingDeploymentsForRunRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ActionsReviewPendingDeploymentsForRunRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ActionsReviewPendingDeploymentsForRunRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ActionsReviewPendingDeploymentsForRunRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ActionsReviewPendingDeploymentsForRunRequest>() {
           @Override
           public void write(JsonWriter out, ActionsReviewPendingDeploymentsForRunRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ActionsReviewPendingDeploymentsForRunRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ActionsReviewPendingDeploymentsForRunRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ActionsReviewPendingDeploymentsForRunRequest
  * @throws IOException if the JSON string is invalid with respect to ActionsReviewPendingDeploymentsForRunRequest
  */
  public static ActionsReviewPendingDeploymentsForRunRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ActionsReviewPendingDeploymentsForRunRequest.class);
  }

 /**
  * Convert an instance of ActionsReviewPendingDeploymentsForRunRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

