/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.ReviewCustomGatesCommentRequired;
import org.openapitools.client.model.ReviewCustomGatesStateRequired;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-09T20:37:23.111113500+10:00[Australia/Brisbane]")
public class ActionsReviewCustomGatesForRunRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ActionsReviewCustomGatesForRunRequest.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ActionsReviewCustomGatesForRunRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ActionsReviewCustomGatesForRunRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ReviewCustomGatesCommentRequired> adapterReviewCustomGatesCommentRequired = gson.getDelegateAdapter(this, TypeToken.get(ReviewCustomGatesCommentRequired.class));
            final TypeAdapter<ReviewCustomGatesStateRequired> adapterReviewCustomGatesStateRequired = gson.getDelegateAdapter(this, TypeToken.get(ReviewCustomGatesStateRequired.class));

            return (TypeAdapter<T>) new TypeAdapter<ActionsReviewCustomGatesForRunRequest>() {
                @Override
                public void write(JsonWriter out, ActionsReviewCustomGatesForRunRequest value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `ReviewCustomGatesCommentRequired`
                    if (value.getActualInstance() instanceof ReviewCustomGatesCommentRequired) {
                        JsonObject obj = adapterReviewCustomGatesCommentRequired.toJsonTree((ReviewCustomGatesCommentRequired)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `ReviewCustomGatesStateRequired`
                    if (value.getActualInstance() instanceof ReviewCustomGatesStateRequired) {
                        JsonObject obj = adapterReviewCustomGatesStateRequired.toJsonTree((ReviewCustomGatesStateRequired)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: ReviewCustomGatesCommentRequired, ReviewCustomGatesStateRequired");
                }

                @Override
                public ActionsReviewCustomGatesForRunRequest read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    // deserialize ReviewCustomGatesCommentRequired
                    try {
                        // validate the JSON object to see if any exception is thrown
                        ReviewCustomGatesCommentRequired.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'ReviewCustomGatesCommentRequired'");
                        ActionsReviewCustomGatesForRunRequest ret = new ActionsReviewCustomGatesForRunRequest();
                        ret.setActualInstance(adapterReviewCustomGatesCommentRequired.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'ReviewCustomGatesCommentRequired'", e);
                    }

                    // deserialize ReviewCustomGatesStateRequired
                    try {
                        // validate the JSON object to see if any exception is thrown
                        ReviewCustomGatesStateRequired.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'ReviewCustomGatesStateRequired'");
                        ActionsReviewCustomGatesForRunRequest ret = new ActionsReviewCustomGatesForRunRequest();
                        ret.setActualInstance(adapterReviewCustomGatesStateRequired.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'ReviewCustomGatesStateRequired'", e);
                    }


                    throw new IOException(String.format("Failed deserialization for ActionsReviewCustomGatesForRunRequest: no class matched. JSON: %s", jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public ActionsReviewCustomGatesForRunRequest() {
        super("anyOf", Boolean.FALSE);
    }

    public ActionsReviewCustomGatesForRunRequest(ReviewCustomGatesCommentRequired o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ActionsReviewCustomGatesForRunRequest(ReviewCustomGatesStateRequired o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("ReviewCustomGatesCommentRequired", new GenericType<ReviewCustomGatesCommentRequired>() {
        });
        schemas.put("ReviewCustomGatesStateRequired", new GenericType<ReviewCustomGatesStateRequired>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return ActionsReviewCustomGatesForRunRequest.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * ReviewCustomGatesCommentRequired, ReviewCustomGatesStateRequired
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof ReviewCustomGatesCommentRequired) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof ReviewCustomGatesStateRequired) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be ReviewCustomGatesCommentRequired, ReviewCustomGatesStateRequired");
    }

    /**
     * Get the actual instance, which can be the following:
     * ReviewCustomGatesCommentRequired, ReviewCustomGatesStateRequired
     *
     * @return The actual instance (ReviewCustomGatesCommentRequired, ReviewCustomGatesStateRequired)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `ReviewCustomGatesCommentRequired`. If the actual instance is not `ReviewCustomGatesCommentRequired`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ReviewCustomGatesCommentRequired`
     * @throws ClassCastException if the instance is not `ReviewCustomGatesCommentRequired`
     */
    public ReviewCustomGatesCommentRequired getReviewCustomGatesCommentRequired() throws ClassCastException {
        return (ReviewCustomGatesCommentRequired)super.getActualInstance();
    }

    /**
     * Get the actual instance of `ReviewCustomGatesStateRequired`. If the actual instance is not `ReviewCustomGatesStateRequired`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ReviewCustomGatesStateRequired`
     * @throws ClassCastException if the instance is not `ReviewCustomGatesStateRequired`
     */
    public ReviewCustomGatesStateRequired getReviewCustomGatesStateRequired() throws ClassCastException {
        return (ReviewCustomGatesStateRequired)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ActionsReviewCustomGatesForRunRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate anyOf schemas one by one
    int validCount = 0;
    // validate the json string with ReviewCustomGatesCommentRequired
    try {
      ReviewCustomGatesCommentRequired.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    // validate the json string with ReviewCustomGatesStateRequired
    try {
      ReviewCustomGatesStateRequired.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    if (validCount == 0) {
      throw new IOException(String.format("The JSON string is invalid for ActionsReviewCustomGatesForRunRequest with anyOf schemas: ReviewCustomGatesCommentRequired, ReviewCustomGatesStateRequired. JSON: %s", jsonObj.toString()));
    }
  }

 /**
  * Create an instance of ActionsReviewCustomGatesForRunRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ActionsReviewCustomGatesForRunRequest
  * @throws IOException if the JSON string is invalid with respect to ActionsReviewCustomGatesForRunRequest
  */
  public static ActionsReviewCustomGatesForRunRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ActionsReviewCustomGatesForRunRequest.class);
  }

 /**
  * Convert an instance of ActionsReviewCustomGatesForRunRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

