/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.AllowedActions;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ActionsRepositoryPermissions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-09T20:37:23.111113500+10:00[Australia/Brisbane]")
public class ActionsRepositoryPermissions {
  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_ALLOWED_ACTIONS = "allowed_actions";
  @SerializedName(SERIALIZED_NAME_ALLOWED_ACTIONS)
  private AllowedActions allowedActions;

  public static final String SERIALIZED_NAME_SELECTED_ACTIONS_URL = "selected_actions_url";
  @SerializedName(SERIALIZED_NAME_SELECTED_ACTIONS_URL)
  private String selectedActionsUrl;

  public ActionsRepositoryPermissions() {
  }

  public ActionsRepositoryPermissions enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Whether GitHub Actions is enabled on the repository.
   * @return enabled
  **/
  @javax.annotation.Nonnull

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public ActionsRepositoryPermissions allowedActions(AllowedActions allowedActions) {
    
    this.allowedActions = allowedActions;
    return this;
  }

   /**
   * Get allowedActions
   * @return allowedActions
  **/
  @javax.annotation.Nullable

  public AllowedActions getAllowedActions() {
    return allowedActions;
  }


  public void setAllowedActions(AllowedActions allowedActions) {
    this.allowedActions = allowedActions;
  }


  public ActionsRepositoryPermissions selectedActionsUrl(String selectedActionsUrl) {
    
    this.selectedActionsUrl = selectedActionsUrl;
    return this;
  }

   /**
   * The API URL to use to get or set the actions and reusable workflows that are allowed to run, when &#x60;allowed_actions&#x60; is set to &#x60;selected&#x60;.
   * @return selectedActionsUrl
  **/
  @javax.annotation.Nullable

  public String getSelectedActionsUrl() {
    return selectedActionsUrl;
  }


  public void setSelectedActionsUrl(String selectedActionsUrl) {
    this.selectedActionsUrl = selectedActionsUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionsRepositoryPermissions actionsRepositoryPermissions = (ActionsRepositoryPermissions) o;
    return Objects.equals(this.enabled, actionsRepositoryPermissions.enabled) &&
        Objects.equals(this.allowedActions, actionsRepositoryPermissions.allowedActions) &&
        Objects.equals(this.selectedActionsUrl, actionsRepositoryPermissions.selectedActionsUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, allowedActions, selectedActionsUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionsRepositoryPermissions {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    allowedActions: ").append(toIndentedString(allowedActions)).append("\n");
    sb.append("    selectedActionsUrl: ").append(toIndentedString(selectedActionsUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("enabled");
    openapiFields.add("allowed_actions");
    openapiFields.add("selected_actions_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("enabled");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ActionsRepositoryPermissions
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ActionsRepositoryPermissions.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ActionsRepositoryPermissions is not found in the empty JSON string", ActionsRepositoryPermissions.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ActionsRepositoryPermissions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ActionsRepositoryPermissions` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ActionsRepositoryPermissions.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("selected_actions_url") != null && !jsonObj.get("selected_actions_url").isJsonNull()) && !jsonObj.get("selected_actions_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `selected_actions_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("selected_actions_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ActionsRepositoryPermissions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ActionsRepositoryPermissions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ActionsRepositoryPermissions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ActionsRepositoryPermissions.class));

       return (TypeAdapter<T>) new TypeAdapter<ActionsRepositoryPermissions>() {
           @Override
           public void write(JsonWriter out, ActionsRepositoryPermissions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ActionsRepositoryPermissions read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ActionsRepositoryPermissions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ActionsRepositoryPermissions
  * @throws IOException if the JSON string is invalid with respect to ActionsRepositoryPermissions
  */
  public static ActionsRepositoryPermissions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ActionsRepositoryPermissions.class);
  }

 /**
  * Convert an instance of ActionsRepositoryPermissions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

