/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.JobStepsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Information of a job execution in a workflow run
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-09T20:37:23.111113500+10:00[Australia/Brisbane]")
public class Job {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_RUN_ID = "run_id";
  @SerializedName(SERIALIZED_NAME_RUN_ID)
  private Integer runId;

  public static final String SERIALIZED_NAME_RUN_URL = "run_url";
  @SerializedName(SERIALIZED_NAME_RUN_URL)
  private String runUrl;

  public static final String SERIALIZED_NAME_RUN_ATTEMPT = "run_attempt";
  @SerializedName(SERIALIZED_NAME_RUN_ATTEMPT)
  private Integer runAttempt;

  public static final String SERIALIZED_NAME_NODE_ID = "node_id";
  @SerializedName(SERIALIZED_NAME_NODE_ID)
  private String nodeId;

  public static final String SERIALIZED_NAME_HEAD_SHA = "head_sha";
  @SerializedName(SERIALIZED_NAME_HEAD_SHA)
  private String headSha;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_HTML_URL = "html_url";
  @SerializedName(SERIALIZED_NAME_HTML_URL)
  private String htmlUrl;

  /**
   * The phase of the lifecycle that the job is currently in.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    QUEUED("queued"),
    
    IN_PROGRESS("in_progress"),
    
    COMPLETED("completed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  /**
   * The outcome of the job.
   */
  @JsonAdapter(ConclusionEnum.Adapter.class)
  public enum ConclusionEnum {
    SUCCESS("success"),
    
    FAILURE("failure"),
    
    NEUTRAL("neutral"),
    
    CANCELLED("cancelled"),
    
    SKIPPED("skipped"),
    
    TIMED_OUT("timed_out"),
    
    ACTION_REQUIRED("action_required");

    private String value;

    ConclusionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConclusionEnum fromValue(String value) {
      for (ConclusionEnum b : ConclusionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ConclusionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConclusionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConclusionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ConclusionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CONCLUSION = "conclusion";
  @SerializedName(SERIALIZED_NAME_CONCLUSION)
  private ConclusionEnum conclusion;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_STARTED_AT = "started_at";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  private OffsetDateTime startedAt;

  public static final String SERIALIZED_NAME_COMPLETED_AT = "completed_at";
  @SerializedName(SERIALIZED_NAME_COMPLETED_AT)
  private OffsetDateTime completedAt;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<JobStepsInner> steps;

  public static final String SERIALIZED_NAME_CHECK_RUN_URL = "check_run_url";
  @SerializedName(SERIALIZED_NAME_CHECK_RUN_URL)
  private String checkRunUrl;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private List<String> labels = new ArrayList<>();

  public static final String SERIALIZED_NAME_RUNNER_ID = "runner_id";
  @SerializedName(SERIALIZED_NAME_RUNNER_ID)
  private Integer runnerId;

  public static final String SERIALIZED_NAME_RUNNER_NAME = "runner_name";
  @SerializedName(SERIALIZED_NAME_RUNNER_NAME)
  private String runnerName;

  public static final String SERIALIZED_NAME_RUNNER_GROUP_ID = "runner_group_id";
  @SerializedName(SERIALIZED_NAME_RUNNER_GROUP_ID)
  private Integer runnerGroupId;

  public static final String SERIALIZED_NAME_RUNNER_GROUP_NAME = "runner_group_name";
  @SerializedName(SERIALIZED_NAME_RUNNER_GROUP_NAME)
  private String runnerGroupName;

  public static final String SERIALIZED_NAME_WORKFLOW_NAME = "workflow_name";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_NAME)
  private String workflowName;

  public static final String SERIALIZED_NAME_HEAD_BRANCH = "head_branch";
  @SerializedName(SERIALIZED_NAME_HEAD_BRANCH)
  private String headBranch;

  public Job() {
  }

  public Job id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of the job.
   * @return id
  **/
  @javax.annotation.Nonnull

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Job runId(Integer runId) {
    
    this.runId = runId;
    return this;
  }

   /**
   * The id of the associated workflow run.
   * @return runId
  **/
  @javax.annotation.Nonnull

  public Integer getRunId() {
    return runId;
  }


  public void setRunId(Integer runId) {
    this.runId = runId;
  }


  public Job runUrl(String runUrl) {
    
    this.runUrl = runUrl;
    return this;
  }

   /**
   * Get runUrl
   * @return runUrl
  **/
  @javax.annotation.Nonnull

  public String getRunUrl() {
    return runUrl;
  }


  public void setRunUrl(String runUrl) {
    this.runUrl = runUrl;
  }


  public Job runAttempt(Integer runAttempt) {
    
    this.runAttempt = runAttempt;
    return this;
  }

   /**
   * Attempt number of the associated workflow run, 1 for first attempt and higher if the workflow was re-run.
   * @return runAttempt
  **/
  @javax.annotation.Nullable

  public Integer getRunAttempt() {
    return runAttempt;
  }


  public void setRunAttempt(Integer runAttempt) {
    this.runAttempt = runAttempt;
  }


  public Job nodeId(String nodeId) {
    
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  @javax.annotation.Nonnull

  public String getNodeId() {
    return nodeId;
  }


  public void setNodeId(String nodeId) {
    this.nodeId = nodeId;
  }


  public Job headSha(String headSha) {
    
    this.headSha = headSha;
    return this;
  }

   /**
   * The SHA of the commit that is being run.
   * @return headSha
  **/
  @javax.annotation.Nonnull

  public String getHeadSha() {
    return headSha;
  }


  public void setHeadSha(String headSha) {
    this.headSha = headSha;
  }


  public Job url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nonnull

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public Job htmlUrl(String htmlUrl) {
    
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  @javax.annotation.Nullable

  public String getHtmlUrl() {
    return htmlUrl;
  }


  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }


  public Job status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * The phase of the lifecycle that the job is currently in.
   * @return status
  **/
  @javax.annotation.Nonnull

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public Job conclusion(ConclusionEnum conclusion) {
    
    this.conclusion = conclusion;
    return this;
  }

   /**
   * The outcome of the job.
   * @return conclusion
  **/
  @javax.annotation.Nullable

  public ConclusionEnum getConclusion() {
    return conclusion;
  }


  public void setConclusion(ConclusionEnum conclusion) {
    this.conclusion = conclusion;
  }


  public Job createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time that the job created, in ISO 8601 format.
   * @return createdAt
  **/
  @javax.annotation.Nonnull

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Job startedAt(OffsetDateTime startedAt) {
    
    this.startedAt = startedAt;
    return this;
  }

   /**
   * The time that the job started, in ISO 8601 format.
   * @return startedAt
  **/
  @javax.annotation.Nonnull

  public OffsetDateTime getStartedAt() {
    return startedAt;
  }


  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }


  public Job completedAt(OffsetDateTime completedAt) {
    
    this.completedAt = completedAt;
    return this;
  }

   /**
   * The time that the job finished, in ISO 8601 format.
   * @return completedAt
  **/
  @javax.annotation.Nullable

  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }


  public void setCompletedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }


  public Job name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the job.
   * @return name
  **/
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Job steps(List<JobStepsInner> steps) {
    
    this.steps = steps;
    return this;
  }

  public Job addStepsItem(JobStepsInner stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Steps in this job.
   * @return steps
  **/
  @javax.annotation.Nullable

  public List<JobStepsInner> getSteps() {
    return steps;
  }


  public void setSteps(List<JobStepsInner> steps) {
    this.steps = steps;
  }


  public Job checkRunUrl(String checkRunUrl) {
    
    this.checkRunUrl = checkRunUrl;
    return this;
  }

   /**
   * Get checkRunUrl
   * @return checkRunUrl
  **/
  @javax.annotation.Nonnull

  public String getCheckRunUrl() {
    return checkRunUrl;
  }


  public void setCheckRunUrl(String checkRunUrl) {
    this.checkRunUrl = checkRunUrl;
  }


  public Job labels(List<String> labels) {
    
    this.labels = labels;
    return this;
  }

  public Job addLabelsItem(String labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Labels for the workflow job. Specified by the \&quot;runs_on\&quot; attribute in the action&#39;s workflow file.
   * @return labels
  **/
  @javax.annotation.Nonnull

  public List<String> getLabels() {
    return labels;
  }


  public void setLabels(List<String> labels) {
    this.labels = labels;
  }


  public Job runnerId(Integer runnerId) {
    
    this.runnerId = runnerId;
    return this;
  }

   /**
   * The ID of the runner to which this job has been assigned. (If a runner hasn&#39;t yet been assigned, this will be null.)
   * @return runnerId
  **/
  @javax.annotation.Nullable

  public Integer getRunnerId() {
    return runnerId;
  }


  public void setRunnerId(Integer runnerId) {
    this.runnerId = runnerId;
  }


  public Job runnerName(String runnerName) {
    
    this.runnerName = runnerName;
    return this;
  }

   /**
   * The name of the runner to which this job has been assigned. (If a runner hasn&#39;t yet been assigned, this will be null.)
   * @return runnerName
  **/
  @javax.annotation.Nullable

  public String getRunnerName() {
    return runnerName;
  }


  public void setRunnerName(String runnerName) {
    this.runnerName = runnerName;
  }


  public Job runnerGroupId(Integer runnerGroupId) {
    
    this.runnerGroupId = runnerGroupId;
    return this;
  }

   /**
   * The ID of the runner group to which this job has been assigned. (If a runner hasn&#39;t yet been assigned, this will be null.)
   * @return runnerGroupId
  **/
  @javax.annotation.Nullable

  public Integer getRunnerGroupId() {
    return runnerGroupId;
  }


  public void setRunnerGroupId(Integer runnerGroupId) {
    this.runnerGroupId = runnerGroupId;
  }


  public Job runnerGroupName(String runnerGroupName) {
    
    this.runnerGroupName = runnerGroupName;
    return this;
  }

   /**
   * The name of the runner group to which this job has been assigned. (If a runner hasn&#39;t yet been assigned, this will be null.)
   * @return runnerGroupName
  **/
  @javax.annotation.Nullable

  public String getRunnerGroupName() {
    return runnerGroupName;
  }


  public void setRunnerGroupName(String runnerGroupName) {
    this.runnerGroupName = runnerGroupName;
  }


  public Job workflowName(String workflowName) {
    
    this.workflowName = workflowName;
    return this;
  }

   /**
   * The name of the workflow.
   * @return workflowName
  **/
  @javax.annotation.Nullable

  public String getWorkflowName() {
    return workflowName;
  }


  public void setWorkflowName(String workflowName) {
    this.workflowName = workflowName;
  }


  public Job headBranch(String headBranch) {
    
    this.headBranch = headBranch;
    return this;
  }

   /**
   * The name of the current branch.
   * @return headBranch
  **/
  @javax.annotation.Nullable

  public String getHeadBranch() {
    return headBranch;
  }


  public void setHeadBranch(String headBranch) {
    this.headBranch = headBranch;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Job job = (Job) o;
    return Objects.equals(this.id, job.id) &&
        Objects.equals(this.runId, job.runId) &&
        Objects.equals(this.runUrl, job.runUrl) &&
        Objects.equals(this.runAttempt, job.runAttempt) &&
        Objects.equals(this.nodeId, job.nodeId) &&
        Objects.equals(this.headSha, job.headSha) &&
        Objects.equals(this.url, job.url) &&
        Objects.equals(this.htmlUrl, job.htmlUrl) &&
        Objects.equals(this.status, job.status) &&
        Objects.equals(this.conclusion, job.conclusion) &&
        Objects.equals(this.createdAt, job.createdAt) &&
        Objects.equals(this.startedAt, job.startedAt) &&
        Objects.equals(this.completedAt, job.completedAt) &&
        Objects.equals(this.name, job.name) &&
        Objects.equals(this.steps, job.steps) &&
        Objects.equals(this.checkRunUrl, job.checkRunUrl) &&
        Objects.equals(this.labels, job.labels) &&
        Objects.equals(this.runnerId, job.runnerId) &&
        Objects.equals(this.runnerName, job.runnerName) &&
        Objects.equals(this.runnerGroupId, job.runnerGroupId) &&
        Objects.equals(this.runnerGroupName, job.runnerGroupName) &&
        Objects.equals(this.workflowName, job.workflowName) &&
        Objects.equals(this.headBranch, job.headBranch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, runId, runUrl, runAttempt, nodeId, headSha, url, htmlUrl, status, conclusion, createdAt, startedAt, completedAt, name, steps, checkRunUrl, labels, runnerId, runnerName, runnerGroupId, runnerGroupName, workflowName, headBranch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Job {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    runUrl: ").append(toIndentedString(runUrl)).append("\n");
    sb.append("    runAttempt: ").append(toIndentedString(runAttempt)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    headSha: ").append(toIndentedString(headSha)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    conclusion: ").append(toIndentedString(conclusion)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    checkRunUrl: ").append(toIndentedString(checkRunUrl)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    runnerId: ").append(toIndentedString(runnerId)).append("\n");
    sb.append("    runnerName: ").append(toIndentedString(runnerName)).append("\n");
    sb.append("    runnerGroupId: ").append(toIndentedString(runnerGroupId)).append("\n");
    sb.append("    runnerGroupName: ").append(toIndentedString(runnerGroupName)).append("\n");
    sb.append("    workflowName: ").append(toIndentedString(workflowName)).append("\n");
    sb.append("    headBranch: ").append(toIndentedString(headBranch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("run_id");
    openapiFields.add("run_url");
    openapiFields.add("run_attempt");
    openapiFields.add("node_id");
    openapiFields.add("head_sha");
    openapiFields.add("url");
    openapiFields.add("html_url");
    openapiFields.add("status");
    openapiFields.add("conclusion");
    openapiFields.add("created_at");
    openapiFields.add("started_at");
    openapiFields.add("completed_at");
    openapiFields.add("name");
    openapiFields.add("steps");
    openapiFields.add("check_run_url");
    openapiFields.add("labels");
    openapiFields.add("runner_id");
    openapiFields.add("runner_name");
    openapiFields.add("runner_group_id");
    openapiFields.add("runner_group_name");
    openapiFields.add("workflow_name");
    openapiFields.add("head_branch");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("run_id");
    openapiRequiredFields.add("run_url");
    openapiRequiredFields.add("node_id");
    openapiRequiredFields.add("head_sha");
    openapiRequiredFields.add("url");
    openapiRequiredFields.add("html_url");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("conclusion");
    openapiRequiredFields.add("created_at");
    openapiRequiredFields.add("started_at");
    openapiRequiredFields.add("completed_at");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("check_run_url");
    openapiRequiredFields.add("labels");
    openapiRequiredFields.add("runner_id");
    openapiRequiredFields.add("runner_name");
    openapiRequiredFields.add("runner_group_id");
    openapiRequiredFields.add("runner_group_name");
    openapiRequiredFields.add("workflow_name");
    openapiRequiredFields.add("head_branch");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Job
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Job.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Job is not found in the empty JSON string", Job.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Job.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Job` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Job.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("run_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `run_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("run_url").toString()));
      }
      if (!jsonObj.get("node_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `node_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("node_id").toString()));
      }
      if (!jsonObj.get("head_sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `head_sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("head_sha").toString()));
      }
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if (!jsonObj.get("html_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `html_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html_url").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (!jsonObj.get("conclusion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `conclusion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("conclusion").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("steps") != null && !jsonObj.get("steps").isJsonNull()) {
        JsonArray jsonArraysteps = jsonObj.getAsJsonArray("steps");
        if (jsonArraysteps != null) {
          // ensure the json data is an array
          if (!jsonObj.get("steps").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `steps` to be an array in the JSON string but got `%s`", jsonObj.get("steps").toString()));
          }

          // validate the optional field `steps` (array)
          for (int i = 0; i < jsonArraysteps.size(); i++) {
            JobStepsInner.validateJsonObject(jsonArraysteps.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("check_run_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `check_run_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("check_run_url").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("labels") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("labels").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `labels` to be an array in the JSON string but got `%s`", jsonObj.get("labels").toString()));
      }
      if (!jsonObj.get("runner_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `runner_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("runner_name").toString()));
      }
      if (!jsonObj.get("runner_group_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `runner_group_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("runner_group_name").toString()));
      }
      if (!jsonObj.get("workflow_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `workflow_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workflow_name").toString()));
      }
      if (!jsonObj.get("head_branch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `head_branch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("head_branch").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Job.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Job' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Job> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Job.class));

       return (TypeAdapter<T>) new TypeAdapter<Job>() {
           @Override
           public void write(JsonWriter out, Job value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Job read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Job given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Job
  * @throws IOException if the JSON string is invalid with respect to Job
  */
  public static Job fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Job.class);
  }

 /**
  * Convert an instance of Job to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

