/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.time.OffsetDateTime;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-09T20:37:23.111113500+10:00[Australia/Brisbane]")
public class RepositoryPushedAt extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(RepositoryPushedAt.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RepositoryPushedAt.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RepositoryPushedAt' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Integer> adapterInteger = gson.getDelegateAdapter(this, TypeToken.get(Integer.class));
            final TypeAdapter<OffsetDateTime> adapterOffsetDateTime = gson.getDelegateAdapter(this, TypeToken.get(OffsetDateTime.class));

            return (TypeAdapter<T>) new TypeAdapter<RepositoryPushedAt>() {
                @Override
                public void write(JsonWriter out, RepositoryPushedAt value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `Integer`
                    if (value.getActualInstance() instanceof Integer) {
                        JsonObject obj = adapterInteger.toJsonTree((Integer)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `OffsetDateTime`
                    if (value.getActualInstance() instanceof OffsetDateTime) {
                        JsonObject obj = adapterOffsetDateTime.toJsonTree((OffsetDateTime)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: Integer, OffsetDateTime");
                }

                @Override
                public RepositoryPushedAt read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize Integer
                    try {
                        // validate the JSON object to see if any exception is thrown
                        Integer.validateJsonObject(jsonObject);
                        actualAdapter = adapterInteger;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'Integer'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for Integer failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'Integer'", e);
                    }

                    // deserialize OffsetDateTime
                    try {
                        // validate the JSON object to see if any exception is thrown
                        OffsetDateTime.validateJsonObject(jsonObject);
                        actualAdapter = adapterOffsetDateTime;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'OffsetDateTime'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for OffsetDateTime failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'OffsetDateTime'", e);
                    }

                    if (match == 1) {
                        RepositoryPushedAt ret = new RepositoryPushedAt();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonObject));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for RepositoryPushedAt: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public RepositoryPushedAt() {
        super("oneOf", Boolean.TRUE);
    }

    public RepositoryPushedAt(Integer o) {
        super("oneOf", Boolean.TRUE);
        setActualInstance(o);
    }

    public RepositoryPushedAt(OffsetDateTime o) {
        super("oneOf", Boolean.TRUE);
        setActualInstance(o);
    }

    static {
        schemas.put("Integer", new GenericType<Integer>() {
        });
        schemas.put("OffsetDateTime", new GenericType<OffsetDateTime>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return RepositoryPushedAt.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Integer, OffsetDateTime
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance == null) {
           super.setActualInstance(instance);
           return;
        }

        if (instance instanceof Integer) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof OffsetDateTime) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Integer, OffsetDateTime");
    }

    /**
     * Get the actual instance, which can be the following:
     * Integer, OffsetDateTime
     *
     * @return The actual instance (Integer, OffsetDateTime)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Integer`. If the actual instance is not `Integer`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Integer`
     * @throws ClassCastException if the instance is not `Integer`
     */
    public Integer getInteger() throws ClassCastException {
        return (Integer)super.getActualInstance();
    }

    /**
     * Get the actual instance of `OffsetDateTime`. If the actual instance is not `OffsetDateTime`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `OffsetDateTime`
     * @throws ClassCastException if the instance is not `OffsetDateTime`
     */
    public OffsetDateTime getOffsetDateTime() throws ClassCastException {
        return (OffsetDateTime)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RepositoryPushedAt
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with Integer
    try {
      Integer.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for Integer failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with OffsetDateTime
    try {
      OffsetDateTime.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for OffsetDateTime failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for RepositoryPushedAt with oneOf schemas: Integer, OffsetDateTime. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonObj.toString()));
    }
  }

 /**
  * Create an instance of RepositoryPushedAt given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RepositoryPushedAt
  * @throws IOException if the JSON string is invalid with respect to RepositoryPushedAt
  */
  public static RepositoryPushedAt fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RepositoryPushedAt.class);
  }

 /**
  * Convert an instance of RepositoryPushedAt to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

