/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ReposCreateDispatchEventRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-09T20:37:23.111113500+10:00[Australia/Brisbane]")
public class ReposCreateDispatchEventRequest {
  public static final String SERIALIZED_NAME_EVENT_TYPE = "event_type";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  private String eventType;

  public static final String SERIALIZED_NAME_CLIENT_PAYLOAD = "client_payload";
  @SerializedName(SERIALIZED_NAME_CLIENT_PAYLOAD)
  private Map<String, Object> clientPayload = new HashMap<>();

  public ReposCreateDispatchEventRequest() {
  }

  public ReposCreateDispatchEventRequest eventType(String eventType) {
    
    this.eventType = eventType;
    return this;
  }

   /**
   * A custom webhook event name. Must be 100 characters or fewer.
   * @return eventType
  **/
  @javax.annotation.Nonnull

  public String getEventType() {
    return eventType;
  }


  public void setEventType(String eventType) {
    this.eventType = eventType;
  }


  public ReposCreateDispatchEventRequest clientPayload(Map<String, Object> clientPayload) {
    
    this.clientPayload = clientPayload;
    return this;
  }

  public ReposCreateDispatchEventRequest putClientPayloadItem(String key, Object clientPayloadItem) {
    if (this.clientPayload == null) {
      this.clientPayload = new HashMap<>();
    }
    this.clientPayload.put(key, clientPayloadItem);
    return this;
  }

   /**
   * JSON payload with extra information about the webhook event that your action or workflow may use. The maximum number of top-level properties is 10.
   * @return clientPayload
  **/
  @javax.annotation.Nullable

  public Map<String, Object> getClientPayload() {
    return clientPayload;
  }


  public void setClientPayload(Map<String, Object> clientPayload) {
    this.clientPayload = clientPayload;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReposCreateDispatchEventRequest reposCreateDispatchEventRequest = (ReposCreateDispatchEventRequest) o;
    return Objects.equals(this.eventType, reposCreateDispatchEventRequest.eventType) &&
        Objects.equals(this.clientPayload, reposCreateDispatchEventRequest.clientPayload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventType, clientPayload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReposCreateDispatchEventRequest {\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    clientPayload: ").append(toIndentedString(clientPayload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("event_type");
    openapiFields.add("client_payload");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("event_type");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReposCreateDispatchEventRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReposCreateDispatchEventRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReposCreateDispatchEventRequest is not found in the empty JSON string", ReposCreateDispatchEventRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ReposCreateDispatchEventRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReposCreateDispatchEventRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReposCreateDispatchEventRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("event_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReposCreateDispatchEventRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReposCreateDispatchEventRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReposCreateDispatchEventRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReposCreateDispatchEventRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ReposCreateDispatchEventRequest>() {
           @Override
           public void write(JsonWriter out, ReposCreateDispatchEventRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReposCreateDispatchEventRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReposCreateDispatchEventRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReposCreateDispatchEventRequest
  * @throws IOException if the JSON string is invalid with respect to ReposCreateDispatchEventRequest
  */
  public static ReposCreateDispatchEventRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReposCreateDispatchEventRequest.class);
  }

 /**
  * Convert an instance of ReposCreateDispatchEventRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

