/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RepositoryRule;
import org.openapitools.client.model.RepositoryRuleEnforcement;
import org.openapitools.client.model.RepositoryRulesetBypassActor;
import org.openapitools.client.model.RepositoryRulesetConditions;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ReposCreateRepoRulesetRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-09T20:37:23.111113500+10:00[Australia/Brisbane]")
public class ReposCreateRepoRulesetRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  /**
   * The target of the ruleset.
   */
  @JsonAdapter(TargetEnum.Adapter.class)
  public enum TargetEnum {
    BRANCH("branch"),
    
    TAG("tag");

    private String value;

    TargetEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TargetEnum fromValue(String value) {
      for (TargetEnum b : TargetEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TargetEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TargetEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TargetEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TargetEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  private TargetEnum target;

  public static final String SERIALIZED_NAME_ENFORCEMENT = "enforcement";
  @SerializedName(SERIALIZED_NAME_ENFORCEMENT)
  private RepositoryRuleEnforcement enforcement;

  /**
   * The permission level required to bypass this ruleset. \&quot;repository\&quot; allows those with bypass permission at the repository level to bypass. \&quot;organization\&quot; allows those with bypass permission at the organization level to bypass. \&quot;none\&quot; prevents anyone from bypassing.
   */
  @JsonAdapter(BypassModeEnum.Adapter.class)
  public enum BypassModeEnum {
    NONE("none"),
    
    REPOSITORY("repository"),
    
    ORGANIZATION("organization");

    private String value;

    BypassModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BypassModeEnum fromValue(String value) {
      for (BypassModeEnum b : BypassModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BypassModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BypassModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BypassModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BypassModeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_BYPASS_MODE = "bypass_mode";
  @SerializedName(SERIALIZED_NAME_BYPASS_MODE)
  private BypassModeEnum bypassMode;

  public static final String SERIALIZED_NAME_BYPASS_ACTORS = "bypass_actors";
  @SerializedName(SERIALIZED_NAME_BYPASS_ACTORS)
  private List<RepositoryRulesetBypassActor> bypassActors;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private RepositoryRulesetConditions conditions;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<RepositoryRule> rules;

  public ReposCreateRepoRulesetRequest() {
  }

  public ReposCreateRepoRulesetRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the ruleset.
   * @return name
  **/
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ReposCreateRepoRulesetRequest target(TargetEnum target) {
    
    this.target = target;
    return this;
  }

   /**
   * The target of the ruleset.
   * @return target
  **/
  @javax.annotation.Nullable

  public TargetEnum getTarget() {
    return target;
  }


  public void setTarget(TargetEnum target) {
    this.target = target;
  }


  public ReposCreateRepoRulesetRequest enforcement(RepositoryRuleEnforcement enforcement) {
    
    this.enforcement = enforcement;
    return this;
  }

   /**
   * Get enforcement
   * @return enforcement
  **/
  @javax.annotation.Nonnull

  public RepositoryRuleEnforcement getEnforcement() {
    return enforcement;
  }


  public void setEnforcement(RepositoryRuleEnforcement enforcement) {
    this.enforcement = enforcement;
  }


  public ReposCreateRepoRulesetRequest bypassMode(BypassModeEnum bypassMode) {
    
    this.bypassMode = bypassMode;
    return this;
  }

   /**
   * The permission level required to bypass this ruleset. \&quot;repository\&quot; allows those with bypass permission at the repository level to bypass. \&quot;organization\&quot; allows those with bypass permission at the organization level to bypass. \&quot;none\&quot; prevents anyone from bypassing.
   * @return bypassMode
  **/
  @javax.annotation.Nullable

  public BypassModeEnum getBypassMode() {
    return bypassMode;
  }


  public void setBypassMode(BypassModeEnum bypassMode) {
    this.bypassMode = bypassMode;
  }


  public ReposCreateRepoRulesetRequest bypassActors(List<RepositoryRulesetBypassActor> bypassActors) {
    
    this.bypassActors = bypassActors;
    return this;
  }

  public ReposCreateRepoRulesetRequest addBypassActorsItem(RepositoryRulesetBypassActor bypassActorsItem) {
    if (this.bypassActors == null) {
      this.bypassActors = new ArrayList<>();
    }
    this.bypassActors.add(bypassActorsItem);
    return this;
  }

   /**
   * The actors that can bypass the rules in this ruleset
   * @return bypassActors
  **/
  @javax.annotation.Nullable

  public List<RepositoryRulesetBypassActor> getBypassActors() {
    return bypassActors;
  }


  public void setBypassActors(List<RepositoryRulesetBypassActor> bypassActors) {
    this.bypassActors = bypassActors;
  }


  public ReposCreateRepoRulesetRequest conditions(RepositoryRulesetConditions conditions) {
    
    this.conditions = conditions;
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @javax.annotation.Nullable

  public RepositoryRulesetConditions getConditions() {
    return conditions;
  }


  public void setConditions(RepositoryRulesetConditions conditions) {
    this.conditions = conditions;
  }


  public ReposCreateRepoRulesetRequest rules(List<RepositoryRule> rules) {
    
    this.rules = rules;
    return this;
  }

  public ReposCreateRepoRulesetRequest addRulesItem(RepositoryRule rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * An array of rules within the ruleset.
   * @return rules
  **/
  @javax.annotation.Nullable

  public List<RepositoryRule> getRules() {
    return rules;
  }


  public void setRules(List<RepositoryRule> rules) {
    this.rules = rules;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReposCreateRepoRulesetRequest reposCreateRepoRulesetRequest = (ReposCreateRepoRulesetRequest) o;
    return Objects.equals(this.name, reposCreateRepoRulesetRequest.name) &&
        Objects.equals(this.target, reposCreateRepoRulesetRequest.target) &&
        Objects.equals(this.enforcement, reposCreateRepoRulesetRequest.enforcement) &&
        Objects.equals(this.bypassMode, reposCreateRepoRulesetRequest.bypassMode) &&
        Objects.equals(this.bypassActors, reposCreateRepoRulesetRequest.bypassActors) &&
        Objects.equals(this.conditions, reposCreateRepoRulesetRequest.conditions) &&
        Objects.equals(this.rules, reposCreateRepoRulesetRequest.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, target, enforcement, bypassMode, bypassActors, conditions, rules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReposCreateRepoRulesetRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    enforcement: ").append(toIndentedString(enforcement)).append("\n");
    sb.append("    bypassMode: ").append(toIndentedString(bypassMode)).append("\n");
    sb.append("    bypassActors: ").append(toIndentedString(bypassActors)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("target");
    openapiFields.add("enforcement");
    openapiFields.add("bypass_mode");
    openapiFields.add("bypass_actors");
    openapiFields.add("conditions");
    openapiFields.add("rules");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("enforcement");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReposCreateRepoRulesetRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReposCreateRepoRulesetRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReposCreateRepoRulesetRequest is not found in the empty JSON string", ReposCreateRepoRulesetRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ReposCreateRepoRulesetRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReposCreateRepoRulesetRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReposCreateRepoRulesetRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("target") != null && !jsonObj.get("target").isJsonNull()) && !jsonObj.get("target").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `target` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target").toString()));
      }
      if ((jsonObj.get("bypass_mode") != null && !jsonObj.get("bypass_mode").isJsonNull()) && !jsonObj.get("bypass_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bypass_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bypass_mode").toString()));
      }
      if (jsonObj.get("bypass_actors") != null && !jsonObj.get("bypass_actors").isJsonNull()) {
        JsonArray jsonArraybypassActors = jsonObj.getAsJsonArray("bypass_actors");
        if (jsonArraybypassActors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("bypass_actors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `bypass_actors` to be an array in the JSON string but got `%s`", jsonObj.get("bypass_actors").toString()));
          }

          // validate the optional field `bypass_actors` (array)
          for (int i = 0; i < jsonArraybypassActors.size(); i++) {
            RepositoryRulesetBypassActor.validateJsonObject(jsonArraybypassActors.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `conditions`
      if (jsonObj.get("conditions") != null && !jsonObj.get("conditions").isJsonNull()) {
        RepositoryRulesetConditions.validateJsonObject(jsonObj.getAsJsonObject("conditions"));
      }
      if (jsonObj.get("rules") != null && !jsonObj.get("rules").isJsonNull()) {
        JsonArray jsonArrayrules = jsonObj.getAsJsonArray("rules");
        if (jsonArrayrules != null) {
          // ensure the json data is an array
          if (!jsonObj.get("rules").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `rules` to be an array in the JSON string but got `%s`", jsonObj.get("rules").toString()));
          }

          // validate the optional field `rules` (array)
          for (int i = 0; i < jsonArrayrules.size(); i++) {
            RepositoryRule.validateJsonObject(jsonArrayrules.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReposCreateRepoRulesetRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReposCreateRepoRulesetRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReposCreateRepoRulesetRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReposCreateRepoRulesetRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ReposCreateRepoRulesetRequest>() {
           @Override
           public void write(JsonWriter out, ReposCreateRepoRulesetRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReposCreateRepoRulesetRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReposCreateRepoRulesetRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReposCreateRepoRulesetRequest
  * @throws IOException if the JSON string is invalid with respect to ReposCreateRepoRulesetRequest
  */
  public static ReposCreateRepoRulesetRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReposCreateRepoRulesetRequest.class);
  }

 /**
  * Convert an instance of ReposCreateRepoRulesetRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

